export const FIREBASE_URL = __ENV.FIREBASE_URL
export const FIREBASE_TREINTA_KEY = __ENV.FIREBASE_TREINTA_KEY
export const FIREBASE_USER = __ENV.FIREBASE_USER
export const FIREBASE_USER_PASSWORD = __ENV.FIREBASE_USER_PASSWORD
export const ORCH_BASE_URL = __ENV.ORCH_BASE_URL
export const USER_ID = __ENV.USER_ID
export const STORE_ID = __ENV.STORE_ID
export const API_KEY = __ENV.API_KEY